import type { Config } from "tailwindcss";
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#00236f", "on-primary": "#ffffff",
        "primary-container": "#1e3a8a", "on-primary-container": "#90a8ff",
        "primary-fixed": "#dce1ff", "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed": "#00164e", "on-primary-fixed-variant": "#264191",
        "inverse-primary": "#b6c4ff",
        "secondary": "#006b5f", "on-secondary": "#ffffff",
        "secondary-container": "#6df5e1", "on-secondary-container": "#006f64",
        "secondary-fixed": "#71f8e4", "secondary-fixed-dim": "#4fdbc8",
        "on-secondary-fixed": "#00201c", "on-secondary-fixed-variant": "#005048",
        "tertiary": "#4b1c00", "on-tertiary": "#ffffff",
        "tertiary-container": "#6e2d00", "on-tertiary-container": "#ff8f4f",
        "tertiary-fixed": "#ffdbca", "tertiary-fixed-dim": "#ffb690",
        "on-tertiary-fixed": "#341100", "on-tertiary-fixed-variant": "#783200",
        "error": "#ba1a1a", "on-error": "#ffffff",
        "error-container": "#ffdad6", "on-error-container": "#93000a",
        "background": "#f8f9fb", "on-background": "#191c1e",
        "surface": "#f8f9fb", "on-surface": "#191c1e",
        "surface-variant": "#e1e2e4", "on-surface-variant": "#444651",
        "surface-container-lowest": "#ffffff", "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0", "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "surface-dim": "#d9dadc", "surface-bright": "#f8f9fb",
        "surface-tint": "#4059aa",
        "outline": "#757682", "outline-variant": "#c5c5d3",
        "inverse-surface": "#2e3132", "inverse-on-surface": "#f0f1f3",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "unit": "8px", "stack-sm": "8px", "stack-md": "16px", "stack-lg": "24px",
        "gutter": "24px", "container-padding-mobile": "16px", "container-padding-desktop": "32px",
      },
      fontFamily: {
        "label-sm": ["Inter","sans-serif"], "label-md": ["Inter","sans-serif"],
        "body-md": ["Inter","sans-serif"], "body-lg": ["Inter","sans-serif"],
        "headline-md": ["Inter","sans-serif"], "headline-lg": ["Inter","sans-serif"],
        "headline-lg-mobile": ["Inter","sans-serif"], "display-lg": ["Inter","sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px",{lineHeight:"16px",letterSpacing:"0.05em",fontWeight:"600"}],
        "label-md": ["14px",{lineHeight:"20px",letterSpacing:"0.01em",fontWeight:"500"}],
        "body-md": ["16px",{lineHeight:"24px",fontWeight:"400"}],
        "body-lg": ["18px",{lineHeight:"28px",fontWeight:"400"}],
        "headline-md": ["24px",{lineHeight:"32px",fontWeight:"600"}],
        "headline-lg-mobile": ["24px",{lineHeight:"32px",fontWeight:"600"}],
        "headline-lg": ["32px",{lineHeight:"40px",letterSpacing:"-0.01em",fontWeight:"600"}],
        "display-lg": ["48px",{lineHeight:"56px",letterSpacing:"-0.02em",fontWeight:"700"}],
      },
    },
  },
  plugins: [],
};
export default config;
